function conditionvec = bingham_logread(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VARNAME3 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  VARNAME3 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VarName3 = importfile("/Users/andreaskeil/Desktop/SSVEP_1st two Ss/Facebor15hzGabor_6002.1.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Nov-2022 16:12:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3", "Var4", "Var5", "Var6"];
opts.SelectedVariableNames = "VarName3";
opts.VariableTypes = ["string", "string", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
conditionvec = [8; 9; tbl.VarName3; 0 ; 0];
end