function convec = getcon_wurz(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WURZLOG104LOG = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  WURZLOG104LOG = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  wurzlog104log = importfile("/Users/arashmirifar/Documents/Wurzburg_2022_3/Mu_reAnalyzing_PrePro/highPass_5-2/wurzburg_104/wurzlog_104_log.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Mar-2024 16:40:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3", "Var4", "Var5", "Var6"];
opts.SelectedVariableNames = "VarName3";
opts.VariableTypes = ["string", "string", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
temp1 = readtable(filename, opts);
convec = table2array(temp1); 

end