% getcon_gaborfeature
% searches condnumbers in *dat file generated by gaborfeatures file

function [con4EEG] = getcon_gaborfeature_new_nina(filepath);

condition = []; 


fid = fopen(filepath)

trialcount = 1;

a = 1
	
 while a > 0
	
     a = fgetl(fid)
     
     if a < 0, break, return, end
        
     block = str2num(a(6))
       
     stimulus = str2num(a(end))

% BELOW: LW, LN, RW, RN = 'right/left - wide/narrow'
% 1 = target, 2 = wide/narrow feature in common, 3 = right/left feature in common, 4 = no features in common
        
            if block ==1, % wide/left
                if stimulus == 1, condition(trialcount) = 1; 
                elseif stimulus ==  '2', condition(trialcount) = 2;
                elseif stimulus ==  '3', condition(trialcount) = 3;
                elseif stimulus ==  '4', condition(trialcount) = 4;
				end
                    
            elseif block ==2, % wide/right
				if stimulus ==      '2', condition(trialcount) = 1; 
				elseif stimulus ==  '1', condition(trialcount) = 2;
				elseif stimulus ==  '4', condition(trialcount) = 3;
				elseif stimulus ==  '3', condition(trialcount) = 4;
				end

             
            elseif block ==3, % narrow/left                
				if stimulus ==      '3', condition(trialcount) = 1; 
				elseif stimulus ==  '4', condition(trialcount) = 2;
				elseif stimulus ==  '1', condition(trialcount) = 3;
				elseif stimulus ==  '2', condition(trialcount) = 4;
				end        

            elseif block ==4, % narrow/right                
				if stimulus ==      '4', condition(trialcount) = 1; 
				elseif stimulus ==  '3', condition(trialcount) = 2;
				elseif stimulus ==  '2', condition(trialcount) = 3;
				elseif stimulus ==  '1', condition(trialcount) = 4;
				end    

			end % if loop for blocks
            

trialcount = trialcount + 1; 
 
end % while loop trials

fclose('all')

con4EEG = condition'; 

eval(['save ' filepath '.con con4EEG -ascii'])
