% getcon_gaborfeature
% searches condnumbers in *dat file generated by rdk_iaps file

function [condvec] = getcon_rdkiaps(filepath);

condvec = []; 

picvec = [];

fid = fopen(filepath)

trialcount = 1;
a = 1
	
 while a > 0
	
     a = fgetl(fid)
     
     if a < 0, break, return, end
        
    
        indexvec = findstr(a, ' ');
        condition = deblank(a(indexvec(3)+1)) %condition file is after 3rd blank (1, 2, or 3)
        
        condvec(trialcount) = str2num(condition)
        
trialcount = trialcount+1
      
end % while loop trials

fclose('all')

 triggervec = condvec'; 
% 

 eval(['save ' filepath '.con triggervec -ascii'])
end
