% getcon_emogabor 
% searches condnumbers and pulls out RTs in *dat file generated by emogabor file
% con1 = pleasant, con2 = neutral, con3 = unpleasant

function [contentRTmat, medianvec] = getcon_emogaborRTEmo(filepath)

correctvec = []; 
contentvec = [];
respvec = [];

fid = fopen(filepath);
trialcount = 1;
a = 1;

while a > 0
    
    a = fgetl(fid)
        
    if a < 0, break, return, end
    
    index1 = findstr(a, 'unpl');
    index3 = findstr(a, 'neut');
    
    picstring1 = a(index1:index1+9);
    picstring3 = a(index3:index3+6);
   
    if strcmp(picstring1,'unpleasant'), contentvec = [contentvec 3];
    elseif strcmp(picstring3,'neutral'), contentvec = [contentvec 2];
    else contentvec = [contentvec 1];
    end
    
    % now.. let's pull out RTs
    blankindex = find(a == ' ');
    respvec = [respvec; str2num(a(blankindex(6)+1:blankindex(7)-1))];
    
    trialcount = trialcount + 1;
    
    % now..... let's pull out the Ns and As
    correctvec = [correctvec; a(blankindex(7)+1)];
    
end % end loop over lines (=trials)

indexpleasantcorrect = find(correctvec == 'A' & contentvec' == 1); 

indexneutralcorrect = find(correctvec == 'A' & contentvec' == 2); 

indexunpleasantcorrect = find(correctvec == 'A' & contentvec' == 3); 


RTvecpleasant  = respvec(indexpleasantcorrect); 

RTvecneutral  = respvec(indexneutralcorrect); 

RTvecunpleasant = respvec(indexunpleasantcorrect); 

figure(1) 

subplot(3,1,1), hist(RTvecpleasant), axis([500 3500 0 10])
subplot(3,1,2), hist(RTvecneutral), axis([500 3500 0 10])
subplot(3,1,3), hist(RTvecunpleasant), axis([500 3500 0 10])



median_pleasant = median(RTvecpleasant); 

median_neutral = median(RTvecneutral); 

median_unpleasant = median(RTvecunpleasant); 

medianvec = [ median_pleasant median_neutral median_unpleasant]




fclose('all')

contentvec = contentvec';

contentRTmat = [contentvec respvec ];

eval(['save ' filepath '.con contentvec -ascii'])

%% stimulus categories
% neutral = [2102 2273 2377 2384 2397 2410 2411 2480 2514 5395 5471 5500 5740 7041 7057 7062 7205 7493 7512 7546];
% pleasant = [1460 1463 1710 1722 1750 2154 2158 2311 2340 2341 4604 4609 4611 4641 4645 4660 4670 4677 4680 4689];
% unpleasant = [3010 3051 3053 3059 3060 3063 3068 3069 3080 3130 3500 3530 6230 6231 6250 6313 6350 6520 6550 6560];
