% getcon_gaborfeature
% searches condnumbers in *dat file generated by gaborfeatures file

function [con4EEG, con4EEGcorrect, meanRT_correct, accuracy, correctRTvec] = getcon_gaborfeature_ECOG(filepath);

condvec = []; 

accuracy = []; 

picvec = [];

fid = fopen(filepath)

trialcount = 1;
a = 1
	
 while a > 0
	
     a = fgetl(fid)
     
     if a < 0, break, return, end
    
     blankindexvec = findstr(a, ' ');
     
     block = str2num(a(blankindexvec(1):blankindexvec(2)));
    
     rt(trialcount) = str2num(a(blankindexvec(3):blankindexvec(4)));
     
        index1 = findstr(a, '.jpg');
        
        conletters = deblank(a(index1-4:index1-2))
        
            if block ==1, 
                if conletters ==      'RLC', condition(trialcount) = 1; 
                elseif conletters ==  'RLO', condition(trialcount) = 2;
                elseif conletters ==  'RRC', condition(trialcount) = 3;
                elseif conletters ==  'RRO', condition(trialcount) = 4;
                elseif conletters ==  'GLC', condition(trialcount) = 5;    
                elseif conletters ==  'GLO', condition(trialcount) = 6;    
                elseif conletters ==  'GRC', condition(trialcount) = 7;
                elseif conletters ==  'GRO', condition(trialcount) = 8;
                end
                    
            elseif block ==2,
                if conletters ==      'RLO', condition(trialcount) = 1; 
                elseif conletters ==  'RLC', condition(trialcount) = 2;
                elseif conletters ==  'RRO', condition(trialcount) = 3;
                elseif conletters ==  'RRC', condition(trialcount) = 4;
                elseif conletters ==  'GLO', condition(trialcount) = 5;    
                elseif conletters ==  'GLC', condition(trialcount) = 6;    
                elseif conletters ==  'GRO', condition(trialcount) = 7;
                elseif conletters ==  'GRC', condition(trialcount) = 8;
                end
             
            elseif block ==3,
                
                if conletters ==      'RRC', condition(trialcount) = 1; 
                elseif conletters ==  'RRO', condition(trialcount) = 2;
                elseif conletters ==  'RLC', condition(trialcount) = 3;
                elseif conletters ==  'RLO', condition(trialcount) = 4;
                elseif conletters ==  'GRC', condition(trialcount) = 5;    
                elseif conletters ==  'GRO', condition(trialcount) = 6;    
                elseif conletters ==  'GLC', condition(trialcount) = 7;
                elseif conletters ==  'GLO', condition(trialcount) = 8; 
                end
                                        
            elseif block ==4,
                
                if conletters ==      'RRO', condition(trialcount) = 1; 
                elseif conletters ==  'RRC', condition(trialcount) = 2;
                elseif conletters ==  'RLO', condition(trialcount) = 3;
                elseif conletters ==  'RLC', condition(trialcount) = 4;
                elseif conletters ==  'GRO', condition(trialcount) = 5;    
                elseif conletters ==  'GRC', condition(trialcount) = 6;    
                elseif conletters ==  'GLO', condition(trialcount) = 7;
                elseif conletters ==  'GLC', condition(trialcount) = 8; 
                end
                    
            elseif block ==5,
                
                if conletters ==      'GLC', condition(trialcount) = 1; 
                elseif conletters ==  'GLO', condition(trialcount) = 2;
                elseif conletters ==  'GRC', condition(trialcount) = 3;
                elseif conletters ==  'GRO', condition(trialcount) = 4;
                elseif conletters ==  'RLC', condition(trialcount) = 5;    
                elseif conletters ==  'RLO', condition(trialcount) = 6;    
                elseif conletters ==  'RRC', condition(trialcount) = 7;
                elseif conletters ==  'RRO', condition(trialcount) = 8;
                end
                    
           elseif block ==6,
                
                if conletters ==      'GLO', condition(trialcount) = 1; 
                elseif conletters ==  'GLC', condition(trialcount) = 2;
                elseif conletters ==  'GRO', condition(trialcount) = 3;
                elseif conletters ==  'GRC', condition(trialcount) = 4;
                elseif conletters ==  'RLO', condition(trialcount) = 5;    
                elseif conletters ==  'RLC', condition(trialcount) = 6;    
                elseif conletters ==  'RRO', condition(trialcount) = 7;
                elseif conletters ==  'RRC', condition(trialcount) = 8;
                end
                    
            elseif block ==7,
                
                if conletters ==      'GRC', condition(trialcount) = 1; 
                elseif conletters ==  'GRO', condition(trialcount) = 2;
                elseif conletters ==  'GLC', condition(trialcount) = 3;
                elseif conletters ==  'GLO', condition(trialcount) = 4;
                elseif conletters ==  'RRC', condition(trialcount) = 5;    
                elseif conletters ==  'RRO', condition(trialcount) = 6;    
                elseif conletters ==  'RLC', condition(trialcount) = 7;
                elseif conletters ==  'RLO', condition(trialcount) = 8;
                end
                    
              elseif block ==8,
                
                if conletters ==      'GRO', condition(trialcount) = 1; 
                elseif conletters ==  'GRC', condition(trialcount) = 2;
                elseif conletters ==  'GLO', condition(trialcount) = 3;
                elseif conletters ==  'GLC', condition(trialcount) = 4;
                elseif conletters ==  'RRO', condition(trialcount) = 5;    
                elseif conletters ==  'RRC', condition(trialcount) = 6;    
                elseif conletters ==  'RLO', condition(trialcount) = 7;
                elseif conletters ==  'RLC', condition(trialcount) = 8;
                end

            end % if loop for blocks
            

trialcount = trialcount + 1; 
 end % while loop trials
  
fclose('all')

contentvec1234 = condition'; 

% calculate accuracy: 
% hits
accuracy.hits = sum(rt < 1.5 & contentvec1234'==1)./sum(contentvec1234'==1)
% false alarms
accuracy.falsealarms = sum(rt < 1.5 & contentvec1234'>1)./sum(contentvec1234'>1)


% create a vector where condition number plus 10 means correct
correcteq1vec = (rt < 1.5 & contentvec1234'==1) + (rt > 1.49999 & contentvec1234'>1);


con4EEG = contentvec1234; 
con4EEGcorrect = contentvec1234 + correcteq1vec'.*10;

% from here, add 127 every 80 trials to accomodate the block start triggers
% in the ECOG data

mat_temp = reshape(con4EEG, 80,8);
vectemp = ones(1,8).*127; 
mat_temp2 = [vectemp; mat_temp]; 

mat_temp_corr = reshape(con4EEGcorrect, 80,8);
vectemp = ones(1,8).*127; 
mat_temp2_corr = [vectemp; mat_temp_corr]; 


con4EEG = reshape(mat_temp2, 648,1);
con4EEGcorrect = reshape(mat_temp2_corr, 648,1);

correctRTvec = rt(rt < 1.5 & contentvec1234'==1);

meanRT_correct = mean(rt(rt < 1.5 & contentvec1234'==1))
stdcorrectRT = std(rt(rt < 1.5 & contentvec1234'==1))

eval(['save ' filepath '.con con4EEG -ascii'])
eval(['save ' filepath '.correct.con con4EEGcorrect -ascii'])





