% getcon_gaborfeature
% searches condnumbers in *dat file generated by gaborfeatures file

function [con4EEG] = getcon_gaborfeature(filepath);

condvec = []; 

picvec = [];

fid = fopen(filepath)

trialcount = 1;
a = 1
	
 while a > 0
	
     a = fgetl(fid)
     
     if a < 0, break, return, end
        
     block = str2num(a(4))
        index1 = findstr(a, '.jpg');
        conletters = deblank(a(index1-5:index1-1));
        
            if block ==1, 
                if conletters == 'RDnHz', condition(trialcount) = 1; 
                elseif conletters ==  'GDnHz', condition(trialcount) = 2;
                elseif conletters ==  'RRtVt', condition(trialcount) = 3;
                elseif conletters ==  'RUpHz', condition(trialcount) = 4;
                elseif conletters ==  'RLtVt', condition(trialcount) = 5;    
                elseif conletters ==  'GUpHz', condition(trialcount) = 6;    
                elseif conletters ==  'GRtVt', condition(trialcount) = 7;
                elseif conletters ==  'GLtVt', condition(trialcount) = 8;
                end
                    
            elseif block ==2,
                if conletters == 'RLtVt', condition(trialcount) = 1; 
                elseif conletters ==  'GLtVt', condition(trialcount) = 2;
                elseif conletters ==  'RUpHz', condition(trialcount) = 3;
                elseif conletters ==  'RRtVt', condition(trialcount) = 4;
                elseif conletters ==  'RDnHz', condition(trialcount) = 5;    
                elseif conletters ==  'GRtVt', condition(trialcount) = 6;    
                elseif conletters ==  'GUpHz', condition(trialcount) = 7;
                elseif conletters ==  'GDnHz', condition(trialcount) = 8;
                end
             
            elseif block ==3,
                
                if conletters == 'RRtVt', condition(trialcount) = 1; 
                elseif conletters ==  'GRtVt', condition(trialcount) = 2;
                elseif conletters ==  'RDnHz', condition(trialcount) = 3;
                elseif conletters ==  'RLtVt', condition(trialcount) = 4;
                elseif conletters ==  'RUpHz', condition(trialcount) = 5;    
                elseif conletters ==  'GLtVt', condition(trialcount) = 6;    
                elseif conletters ==  'GDnHz', condition(trialcount) = 7;
                elseif conletters ==  'GUpHz', condition(trialcount) = 8; 
                end
                                        
            elseif block ==4,
                
                if conletters == 'RUpHz', condition(trialcount) = 1; 
                elseif conletters ==  'GUpHz', condition(trialcount) = 2;
                elseif conletters ==  'RLtVt', condition(trialcount) = 3;
                elseif conletters ==  'RDnHz', condition(trialcount) = 4;
                elseif conletters ==  'RRtVt', condition(trialcount) = 5;    
                elseif conletters ==  'GDnHz', condition(trialcount) = 6;    
                elseif conletters ==  'GLtVt', condition(trialcount) = 7;
                elseif conletters ==  'GRtVt', condition(trialcount) = 8; 
                end
                    
            elseif block ==5,
                
                if conletters == 'GDnHz', condition(trialcount) = 1; 
                elseif conletters ==  'RDnHz', condition(trialcount) = 2;
                elseif conletters ==  'GRtVt', condition(trialcount) = 3;
                elseif conletters ==  'GUpHz', condition(trialcount) = 4;
                elseif conletters ==  'GLtVt', condition(trialcount) = 5;    
                elseif conletters ==  'RUpHz', condition(trialcount) = 6;    
                elseif conletters ==  'RRtVt', condition(trialcount) = 7;
                elseif conletters ==  'RLtVt', condition(trialcount) = 8;
                end
                    
           elseif block ==6,
                
                if conletters == 'GLtVt', condition(trialcount) = 1; 
                elseif conletters ==  'RLtVt', condition(trialcount) = 2;
                elseif conletters ==  'GUpHz', condition(trialcount) = 3;
                elseif conletters ==  'GRtVt', condition(trialcount) = 4;
                elseif conletters ==  'GDnHz', condition(trialcount) = 5;    
                elseif conletters ==  'RRtVt', condition(trialcount) = 6;    
                elseif conletters ==  'RUpHz', condition(trialcount) = 7;
                elseif conletters ==  'RDnHz', condition(trialcount) = 8;
                end
                    
            elseif block ==7,
                
                if conletters == 'GRtVt', condition(trialcount) = 1; 
                elseif conletters ==  'RRtVt', condition(trialcount) = 2;
                elseif conletters ==  'GDnHz', condition(trialcount) = 3;
                elseif conletters ==  'GLtVt', condition(trialcount) = 4;
                elseif conletters ==  'GUpHz', condition(trialcount) = 5;    
                elseif conletters ==  'RLtVt', condition(trialcount) = 6;    
                elseif conletters ==  'RDnHz', condition(trialcount) = 7;
                elseif conletters ==  'RUpHz', condition(trialcount) = 8;
                end
                    
              elseif block ==8,
                
                if conletters == 'GUpHz', condition(trialcount) = 1; 
                elseif conletters ==  'RUpHz', condition(trialcount) = 2;
                elseif conletters ==  'GLtVt', condition(trialcount) = 3;
                elseif conletters ==  'GDnHz', condition(trialcount) = 4;
                elseif conletters ==  'GRtVt', condition(trialcount) = 5;    
                elseif conletters ==  'RDnHz', condition(trialcount) = 6;    
                elseif conletters ==  'RLtVt', condition(trialcount) = 7;
                elseif conletters ==  'RRtVt', condition(trialcount) = 8;
                end

            end % if loop for blocks
            

trialcount = trialcount + 1; 
 end % while loop trials

fclose('all')

contentvec1234 = condition'; 

con4EEG = contentvec1234; 

eval(['save ' filepath '.con con4EEG -ascii'])
