% getcon_emogaborRT
% pull out RT data in *dat file generated by emogabor file
% con3 = unpleasant, con1 = pleasant, con2 = neutral

function [respvec] = getcon_emogaborRT(filepath)

respvec = [];

fid = fopen(filepath);
trialcount = 1;
a = 1;

while a > 0
    a = fgetl(fid)
        
    if a < 0, break, return, end
        
    blankindex = find(a == ' ');
    respvec = [respvec; str2num(a(blankindex(6)+1:blankindex(7)-1))];
      
    trialcount = trialcount + 1;
       
end % end loop over lines (=trials)


fclose('all')

eval(['save ' filepath '.con respvec -ascii'])
