% getcon_gaborfeature
% searches condnumbers in *dat file generated by gaborfeatures file

function [conditionvec] = getcon_ssvepudfaces(filepath);

condvec = []; 

picvec = [];

fid = fopen(filepath)

trialcount = 1;
a = 1
	
 while a > 0
	
     a = fgetl(fid)
     
     if a < 0, break, return, end
        
         blankindex = find(a == ' '); 
     
            condnum1 = str2num(a(blankindex(2)+1))
            
            conletter = deblank(a(blankindex(4)+1));
        
          if conletter == 'A', condnum2 = 10;  
          elseif conletter == 'U', condnum2 = 20; 
          end  % if loop for condition 2
              
       conditionvec(trialcount) =    condnum1 + condnum2; 
            

trialcount = trialcount + 1; 
 end % while loop trials

fclose('all')

conditionvec = conditionvec';

eval(['save ' filepath '.con conditionvec -ascii'])




