% searches condnumbers in *dat file generated by rdkiaps file

function []=getresponse_rdk_ETI(filemat); %filepat = .dat file 
% can print out all of this...function [ conditionvec, RT, errorvec, onsettime, targetvec, earlylatelabel, picvec, outmat, RTvecEarlyLate, correctvec] = getresponse_rdk(filepath);

alltrialindexvec = 1:90; alltrialindexvec = alltrialindexvec'; 

oumat_all = [];

for fileindex = 1:size(filemat,1); 

    filepath = deblank(filemat(fileindex,:))

    condvec = []; 

    picvec = [];

    fid = fopen(filepath);

    trialcount = 1;
    
a = 1;
	
 while a > 0
	
     a = fgetl(fid);
     
     if a < 0, break, return, end
            
     % find the blanks - > so I know where the picture name is 
     blankindices = find(a== ' '); 
     
      conditionTar = deblank(a(blankindices(3)+1)); %target/non-target condition file is after 3rd blank (1, 2, or 3)
      
      targetvec(trialcount) = str2num(conditionTar);
      
      onsettimetemp = deblank(a(blankindices(4):blankindices(4)+2));
      
      onsettime(trialcount) = str2num(onsettimetemp).*133.333 - 133.333 -1000;
            
     
     picturestring = (a((blankindices(7)+1:blankindices(7)+2))); %get the picture name info after the 7th blank
     picturestring_long = (a((blankindices(7)+1:blankindices(7)+4))); %get the picture name info after the 7th blank
     picvec = [picvec; picturestring_long];
     
     
     rt(trialcount) = str2num(a(blankindices(6):blankindices(7))); %get the RT info after the 6th blank
     
     if rt(trialcount) < 0, rt(trialcount) = rt(trialcount)+ 8751; end %8751 is the average tic/toc for trial length. Here we're using the ONSET of the 4 flick cycles for RT info   
          
               if picturestring ==  'er', condition(trialcount) = 1;
                elseif picturestring ==  'ct', condition(trialcount) = 1;    
                elseif picturestring ==  'ca', condition(trialcount) = 1;
                elseif picturestring ==  'wr', condition(trialcount) = 2;
                elseif picturestring ==  'wk', condition(trialcount) = 2;
                elseif picturestring ==  'cw', condition(trialcount) = 2;
                elseif picturestring ==  'co', condition(trialcount) = 2; 
                elseif picturestring ==  'mu', condition(trialcount) = 3;
                elseif picturestring ==  'mt', condition(trialcount) = 3;    
                elseif picturestring ==  'sn', condition(trialcount) = 3;
                
                end
      
              trialcount;
 
              
trialcount = trialcount + 1; 
 end % while loop trials
 
 % DONE READING THE FILE
 
fclose('all')
  
targetvec = targetvec' .* 100

conditionvec = condition' + targetvec; 
  
conditionvec1to3 = condition'; %condition = picture conditions, 

rt = rt' .*0.001; %change RT into seconds

onsettime = onsettime' .*0.001 %change onset time also into seconds

RT = rt;
RT(rt>0) = rt(rt>0)-onsettime(rt>0)% convert rt relative to picture offset to RT relative to target
%RT = RT' %this is to account for non-presses when a non-target (corr.
%rejections) .. auto put RT for non-target as 0.116 and had to make sure all non-press RT's are set to ZERO

pause

duringpiclabel  = zeros(size(RT)); 
duringpiclabel(onsettime>3) = 1;

conditionvecPicRT =[conditionvec  RT]; % can use a semi-colon to have the conditionvec and RT values not stacked but side by side 
size(conditionvec);

% %create a vector that has 1s for correct responses, for each trial
indexvec_press = find(RT > .15)
correctvec = zeros(size(condition)); %empty vector to populate

targettrialindices = find(targetvec > 199 & targetvec <  299) %299 excludes the double-flick trials
notargettrialindices = find(targetvec > 99 & targetvec <  199); %excludes the double-flick trials and the one-target trials

% FIRST LOOK AT TARGETS
targettrialindices_picon = targettrialindices(logical(duringpiclabel(targettrialindices)))

%  the original code had x2 as = 1 also, but it should be zero...
for x1 = 1:length(correctvec) 
    ismember(x1,targettrialindices_picon)
    ismember(x1,indexvec_press)
    if ismember(x1,targettrialindices_picon) && ismember(x1,indexvec_press), correctvec(x1) = 1; end %correct response = 1
    
end


% find subpopulation of trial in P N U and look how many are correct
indices_p_picon = find(conditionvec1to3(targettrialindices_picon) ==3); 

%how many of those are correct
hits_p = correctvec(targettrialindices_picon(indices_p_picon))



%if its not a target trial and they didn't press after 150 ms, incorrect
for x2 = 1:length(correctvec) 
    if ~ismember(x2,targettrialindices) && ismember(x2,indexvec_press), correctvec(x2) = 0; end %incorrect response = 0 
end



end