function [t_within, t_between] = jackknife_ttest(invec1, invec2); 

%%%%% WITHIN

% within-subjects ttest with jackknifing. needs input generated by
% get_jacknifevec

% calculate mean Difference D

D = mean(invec1) - mean(invec2)


% calculate Sd_jacknife eq 2 in miller, patterson, ulrich, 1998 

N = size(invec1,1);

%Sd = sqrt(((N-1)/N) .* sum(((invec1-invec2)-D).^2))

Sd = sqrt(((N-1)/N) .* sum(((invec1-invec2)-D).^2))

t_within = D./Sd;


%%%%% BETWEEN

% calculate uncorrected between T

[H,P,CI,STATS] = ttest2(invec1, invec2);

t_between = STATS.tstat;